baseurl = "https://tbradley1013.github.io/"
languageCode = "en-us"
title = "goonR blog"
author = "Tyler Bradley"
theme = "blackburn"
canonifyurls = true
paginate = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
plugins = "jekyll-seo-tag"
publishDir = "../tbradley1013.github.io"
rssLimit = 10

[permalinks]
    post = "/:year/:month/:day/:slug/"

[indexes]
  tag = "tags"
  topic = "topics"


[params]
  subtitle = "A blog about R by an Arsenal fan"
  description = "A blog about R by an Arsenal fan"
  disqus = "goonR-blog"
  googleAnalytics = "UA-115670447-2"
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["r", "yaml"]
  dateFormat = "02 Jan 2006"
  logo = "headshot-tyler-bradley-small.jpg"
  


[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "R"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 3
    identifer = "r"
    url = "/tags/rstats/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 4
    identifier = "tag"
    url = "/tags/"
  [[menu.main]]
    name = "Publications"
    pre = "<i class='fa fa-book fa-fw'></i>"
    weight = 5
    identifier = "publications"
    url = "/publications/"
  [[menu.main]]
    name = "Presentations"
    pre = "<i class='fa fa-laptop fa-fw'></i>"
    weight = 6
    identifier = "presentations"
    url = "/presentations/"
  [[menu.main]]
    name = "Resources"
    pre = "<i class='fa fa-bookmark fa-fw'></i>"
    weight = 7
    identifier = "resources"
    url = "/resources/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 8
    identifier = "about"
    url = "/about/"

    
    
[social]
  twitter = "tycbrad"
  github = "tbradley1013"
  stackoverflow = "7133355"
  linkedin = "tyler-bradley-68707292/"
  rstudiocommunity = "tbradley/summary"






