baseurl = "/"
languageCode = "en-us"
title = "goonR blog"
author = "Tyler Bradley"
theme = "blackburn"
canonifyurls = true
paginate = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
plugins = "jekyll-seo-tag"
publishDir = "../tbradley1013.github.io"


[permalinks]
    post = "/:year/:month/:day/:slug/"

[indexes]
  tag = "tags"
  topic = "topics"


[params]
  subtitle = "A blog about R by an Arsenal fan"
  disqus = "goonR-blog"
  googleAnalytics = "UA-115670447-2"
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["r", "yaml"]
  dateFormat = "02 Jan 2006"
  


[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "RStudio Community"
    weight = 4
    url = "https://community.rstudio.com/u/tbradley/summary"
    
    
[social]
  twitter = "tycbrad"
  github = "tbradley1013"
  stackoverflow = "7133355"
  linkedin = "tyler-bradley-68707292/"






