baseurl = "https://tbradley1013.github.io"
languageCode = "en-us"
title = "goonR blog"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = "goonR-blog"
publishDir = "../tbradley1013.github.io"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
plugins = "jekyll-seo-tag"


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/tbradley1013"
    weight = 2
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/tycbrad"
    weight = 3
[[menu.main]]
    name = "RStudio Community"
    url = "https://community.rstudio.com/u/tbradley/summary"
    weight = 4
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/tyler-bradley-68707292/"
    weight = 5
[[menu.main]]
    name = " R-Bloggers"
    url = "https://www.r-bloggers.com/"
    weight = 6

[params]
    description = "A Blog site about R and data science by an Arsenal Fan"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "arsenal-buttton.jpg"
    width = 30
    height = 50
    alt = "Logo"


